version: '3'

services:
  roach1:
    image: cockroachdb/cockroach:v22.1.10
    networks:
      - roachnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach1-data:/cockroach/cockroach-data
      - ./database_entrypoint/:/docker-entrypoint-initdb.d/
    command: "start-single-node --insecure"
    healthcheck:
      test: [ "curl", "http://localhost:8080/health" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  gobblerd:
    image: gobblerd:latest
    ports:
      - "80:8080"
    networks:
      - roachnet
    environment:
      - GOBBLER_DB_USERNAME=root
      - GOBBLER_DB_HOST=roach1
      - GOBBLER_DB_PORT=26257
      - GOBBLER_DB_DATABASE=gobb_dev
      - GOBBLER_DB_SSL_MODE=disable

networks:
  roachnet:


volumes:
  roach1-data:
